services:
  db: # PostgreSQL database service
    image: postgres:18-alpine # Uses the official postgres docker image
    container_name: library-postgres
    environment: # Values injected from the .env file
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data volume
      - ./src/main/resources/db/migration/V1_create_books_table.sql:/docker-entrypoint-initdb.d/V1_create_books_table.sql # Runs DB schema init on first startup
    restart: unless-stopped

  app: # Spring Boot application service
    build: . # Builds image locally via dockerfile
    container_name: library-app
    depends_on: # Ensures that the database starts first before the app
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB} # References the db container above
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080" # Maps host port 8080 to container port 8080
    restart: unless-stopped

volumes:
  postgres_data: # Define the name of the docker volume
